channels:
- conda-forge
dependencies:
- python=3.7.12
- pip
- pip:
  - mlflow
  - cloudpickle==1.3.0
  - pathlib==1.0.1
  - psutil==5.4.8
  - scikit-learn==0.0
  - scikit-learn==0.22.2.post1
  - typing-extensions==3.7.4.3
name: mlflow-env
